import XCTest
@testable import Output

final class OutputTests: XCTestCase {
  
  func testSuccessDescription() {
    XCTAssertEqual(LogMessage.success("Stored data successfully!").description, "‚úÖ Stored data successfully!")
  }
  
  func testWarningDescription() {
    XCTAssertEqual(LogMessage.warning("Content should not have a prefix of whitespace").description, "‚ö†Ô∏è Content should not have a prefix of whitespace")
  }
  
  func testFailureDescription() {
    XCTAssertEqual(LogMessage.failure("Network request failed").description, "‚ùå Network request failed")
  }
  
  func testMessageDescription() {
    XCTAssertEqual(LogMessage.message(["My", "list", "of", "strings"]).description, "üí¨ [\"My\", \"list\", \"of\", \"strings\"]")
  }
  
  func testCancelledDescription() {
    XCTAssertEqual(LogMessage.cancelled("Network request cancelled").description, "‚õî Network request cancelled")
  }
  
  func testFinishedDescription() {
    XCTAssertEqual(LogMessage.finished("Finished synchronisation task").description, "üèÅ Finished synchronisation task")
  }
  
  func testSuccessfulResult() {
    let result: Result<Any, Error> = .success("Success!")
    XCTAssertEqual(result.logMessage.description, "‚úÖ Success!")
  }
  
  enum TestError: Error {
    case any
  }
  
  func testFailureResult() {
    let result: Result<Any, Error> = .failure(TestError.any)
    XCTAssertEqual(result.logMessage.description, "‚ùå any")
  }

  static var allTests = [
    ("testSuccessDescription", testSuccessDescription),
    ("testWarningDescription", testWarningDescription),
    ("testFailureDescription", testFailureDescription),
    ("testMessageDescription", testMessageDescription),
    ("testCancelledDescription", testCancelledDescription),
    ("testFinishedDescription", testFinishedDescription)
  ]
}
